// storefront/src/modules/home/components/hero/index.tsx
import Carousel from "./Carousel"

const Hero = () => {
  const slides = [
    { image: "/swiper/swiper1.jpg", caption: "Caption 1" },
    { image: "/swiper/swiper2.jpg", caption: "Caption 2" },
    { image: "/swiper/swiper3.jpg", caption: "Caption 3" },
  ]

  return (
    <div className="flex flex-col md:flex-row items-stretch gap-6 lg:gap-8 mx-1.5 lg:mx-[clamp(6px,1vw+3rem,49px)]">
      {/* Hero Text Section */}
      <div className="flex-1 flex flex-col justify-center bg-brand-brown px-2.5 pt-9 pb-11 pl-7 rounded-[46px] max-w-full md:max-w-[799px]">
        <h2 className="mt-2 text-7xl text-brand-white font-bodoni font-normal optical-size-small">
          Forge Elidor
        </h2>
        <h1 className="text-[84px] text-brand-white font-sans font-black uppercase">
          Coutelier dans la Vallée de Munster
        </h1>
        <p className="mt-6 text-2xl text-brand-white font-sans font-normal">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor consequat ligula, sit amet
          vestibulum mi consequat a. Mauris sollicitudin ligula sit amet elit bibendum, id consequat lorem hendrerit.
        </p>
        <div className="mt-9">
          <a
            href="#"
            className="inline-block text-brand-black no-underline font-sans font-medium bg-brand-light py-2.5 px-9 rounded-full text-2xl hover:bg-opacity-90 transition-all"
          >
            Voir Plus
          </a>
        </div>
      </div>

      {/* Carousel Section */}
      <Carousel slides={slides} className="flex-1" />
    </div>
  )
}

export default Hero

// src/app/component/composant/pages/home/hero/hero.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-hero',
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.scss'
})
export class HeroComponent implements OnInit, OnDestroy{

  slides = [
    { image: '../../../../assets/images/swiper/swiper1.jpg', caption: 'Caption 1' },
    { image: '../../../../assets/images/swiper/swiper2.jpg', caption: 'Caption 2' },
    { image: '../../../../assets/images/swiper/swiper3.jpg', caption: 'Caption 3' }
  ];
  currentSlide = 0;
  intervalId: any;

  ngOnInit() {
    this.startAutoSlide();
  }

  ngOnDestroy() {
    this.stopAutoSlide();
  }

  startAutoSlide() {
    this.intervalId = setInterval(() => {
      this.nextSlide();
    }, 5000);
  }

  stopAutoSlide() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  prevSlide() {
    this.currentSlide = (this.currentSlide > 0) ? this.currentSlide - 1 : this.slides.length - 1;
  }

  nextSlide() {
    this.currentSlide = (this.currentSlide < this.slides.length - 1) ? this.currentSlide + 1 : 0;
  }

  goToSlide(index: number) {
    this.currentSlide = index;
  }
}

<section>
    <div class="container-hero">
        <h2>Forge Elidor</h2>
        <h1>COUTELIER DANS LA VALLÉE DE MUNSTER</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor consequat ligula, sit amet
            vestibulum mi consequat a. Mauris sollicitudin ligula sit amet elit bibendum, id consequat lorem hendrerit.
        </p>
        <div class="btn">
            <a href="#">Voire Plus</a>
        </div>
    </div>

    <div class="container-slider">

        <div class="swiper-container">
            <div class="swiper" [style.transform]="'translateX(' + currentSlide * -100 + '%)'">
                <div class="slide" *ngFor="let slide of slides">
                    <img [src]="slide.image" [alt]="slide.caption">
                </div>
            </div>

            <div class="container-controleur">
                <div class="container-btn">
                    <button (click)="prevSlide()"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-move-up"><path d="M8 6L12 2L16 6"/><path d="M12 2V22"/></svg></button>
                    <button class="arrow-nex"  (click)="nextSlide()"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-move-down"><path d="M8 18L12 22L16 18"/><path d="M12 2V22"/></svg></button>
                </div>

                <div class="pagination">
                    <span *ngFor="let slide of slides; let i = index" [class.active]="i === currentSlide"
                        (click)="goToSlide(i)"></span>
                </div>
            </div>
        </div>


        <div class="rond-voir-plus">
            <img src="../../../../../../assets/icons/swiper/rond-voire-plus.svg" alt="">
            <img src="../../../../../../assets/icons/swiper/arrow.svg" alt="">
        </div>
    </div>


</section>
